apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f services.yml
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: identity-service
  name: identity-service
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f services.yml
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        io.kompose.service: identity-service
    spec:
      containers:
      - image: compose_pacco.services.identity
        name: identity-service
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
status: {}
